### ISSUE TITLE
No such file or directory: '../data/formal_manual_selection/task_id_dicts/30_selected.pkl'

### ISSUE THREAD

**Issue by cc13qq** [OSU-NLP-Group/SeeAct#10]
Thank you for your demo. I tried to generate screenshots but I didn't find these files:  "../data/formal_manual_selection/task_id_dicts/30_selected.pkl"
"../data/source_data/20_chocies/test_website_outputs_top50.json"
Look forward to your reply.

**Comment by boyuanzheng010** [comment]
Hi @cc13qq , thanks for your interest in our work. 
You could refer to #9 for relevant resources.
