### ISSUE TITLE
Evaluation for element attributes and image annotations

### ISSUE THREAD

**Issue by cc13qq** [OSU-NLP-Group/SeeAct#13]
Thank you for your newly updated files! I have successfully generated screenshots.

However, I'm still curious about how to evaluate the element attributes and image annotations since the outputs of SeeAct are not predicted choices.
I didn't find the ground truth of these two splits.

Are you also planning to release the evaluation code for element attributes and image annotations? 

Look forward to your reply.

**Comment by boyugou** [comment]
The evaluation for image_annotation is identical to text_choice, since they are using the same choice candidates. For element attributes we have also described in the paper.

For the later upgrades of SeeAct codebase, I replied in #14.

Thanks for your interest in our work!
