### ISSUE TITLE
Model trajectories release

### ISSUE THREAD

**Issue by taogoddd** [OSU-NLP-Group/SeeAct#16]
Dear Authors,

Thank you for this brilliant work. I want to do some analysis on the trajectories of different methods in your paper (e.g. FLAN-T5, GPT-4, SeeAct with different grounding methods). Is it possible to release any of the trajectories? That would be meaningful for much future work!

Thanks in advance!

**Comment by boyuanzheng010** [comment]
Thanks for your interest in our work! We have cleaned out the trajectories in this [one drive link](https://urldefense.com/v3/__https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/gou_43_buckeyemail_osu_edu/ES-DJvgMAWVKjIaajx8pAyYBAIpNwsx2ugBOcP7AtDpgdg?e=Lbf9so__;!!KGKeukY!zEURVbkP8RMmrvL1FDKZglBB-Qy3aCmEdL5N2ytBZll3Nuykk71PD1sjQCHDejV0e-JJj2OfzLUArX1HlfiiulXN_r2BpIA$).
