### ISSUE TITLE
Looking to test this against my website

### ISSUE THREAD

**Issue by Shoshin23** [OSU-NLP-Group/SeeAct#2]
Hi, 

I'm working in the accessibility space and I find the work you're doing to be extremely useful there. Can you tell me how I can run this project against my website? An agent that understands queries and completes them for me? 

I'm trying to piece it together thru the code but you might be able to help me better. 

Thanks!

**Comment by boyugou** [comment]
Accessibility was indeed a great application for the web navigation assistant we thought of when we were working on Mind2Web in the early days. Regarding this script, we will release it around Friday. Please don't worry, running it will be very simple, you just need to enter the website and task. Its capabilities are not perfect, but it's worth a try.

**Comment by Shoshin23** [comment]
Thanks! looking forward to trying it out. :)
