### ISSUE TITLE
Config not loaded?

### ISSUE THREAD

**Issue by manuel-delverme** [OSU-NLP-Group/SeeAct#27]
https://github.com/OSU-NLP-Group/SeeAct/blob/9d2fba437b8bb83f34e565122dbd47e59fc319cc/seeact_package/seeact/agent.py#L68C1-L71C1

Is this a bug or am i misunderstanding the code?

**Comment by boyugou** [comment]
We haven't finished the documentation for the package, and also there might be some bugs.

However, let me explain the logic here.

In the initialization, you can either input a TOML file as a config file or use the default configuration. (You can change the default settings by passing the parameters.)

**Comment by manuel-delverme** [comment]
wouldn't you have `config = toml.load(blah)` in there?

**Comment by boyugou** [comment]
ok, I forgot about that. (probably deleted it mistakenly). You are totally right.
