### ISSUE TITLE
Statement has no effect

### ISSUE THREAD

**Issue by manuel-delverme** [OSU-NLP-Group/SeeAct#30]
https://github.com/OSU-NLP-Group/SeeAct/blob/8af310159af97b123ff07abb925c497bb1ca2478/src/data_utils/format_prompt_utils.py#L204

Sorry It's harder for me to do a PR, I'm working on another codebase

**Comment by boyuanzheng010** [comment]
Thanks @manuel-delverme . We will clean this code in new version.
