### ISSUE TITLE
Mistake or workaround?

### ISSUE THREAD

**Issue by manuel-delverme** [OSU-NLP-Group/SeeAct#34]
https://github.com/OSU-NLP-Group/SeeAct/blob/fcba5ba2fe6a961bb5696e70aa829db68ce500df/seeact_package/seeact/agent.py#L406-L407

Why do we need to call fill twice?

**Comment by boyugou** [comment]
On some website's some elements, I don't know why, but it will not actually fill in the text if only do it once. 

(It will be great if someone can tell me why. I remember what I tested is the zip code area of [thumbtack](https://www.thumbtack.com/#:~:text=made%20easy.-,HIRE%20A%20PRO,-FIND%20CUSTOMERS))
