### ISSUE TITLE
SeaAct cannot find screenshot of the page

### ISSUE THREAD

**Issue by vbxx0** [OSU-NLP-Group/SeeAct#36]
Hello guys! 
I have a problem launching example script on my website.
FileNotFoundError: [Errno 2] No such file or directory: 'seeact_agent_files/20240608_162057/screenshots/screen_1.png'

```python
async def run_agent():
    agent = SeeActAgent(model="gpt-4-turbo",
                        default_task=TASK,
                        default_website=WEBSITE,
                        # save_file_dir="/tmp/test"
                        )
    await agent.start()
    while not agent.complete_flag:
        prediction_dict = await agent.predict()
        await agent.execute(prediction_dict)
    await agent.stop()


if __name__ == "__main__":
    asyncio.run(run_agent())
```
I didn't find any screenshots in the given folder, but found logs (website name was replaced)
![image](https://github.com/OSU-NLP-Group/SeeAct/assets/152014127/226654a6-02e6-4037-8ffe-943bcc888200)

As for google.com this works fine

**Comment by boyugou** [comment]
because you are opening "example.com", which is not an actual web page?

**Comment by vbxx0** [comment]
@boyugou I replaced for the issue but its https://app.usebraintrust.com/jobs/12636

**Comment by boyugou** [comment]
Interestingly, I also failed to take screenshots of this webpage for the first time (succeeded the second time). Will try to figure out the reason.

**Comment by vbxx0** [comment]
> Interestingly, I also failed to take screenshots of this webpage for the first time (succeeded the second time). Will try to figure out the reason.

I believe it's a playwright issue. I think it will be useful to make ability to provide my own playwright instance (for example if I need playwright-stealth)
