### ISSUE TITLE
som branch has duplicate overlays

### ISSUE THREAD

**Issue by mlin12321** [OSU-NLP-Group/SeeAct#39]
The som branch (commit 6900592) creates duplicate element labels for certain actions on certain websites. For example, for tasks that involve scrolling down on twitter, the labels will still persist. This appears to be the case for actions on the same page (e.g. scrolling)

**Comment by duz-sg** [comment]
This issue is because the marks are cleared too late (before next round of mark generation), therefore, whenever the page changes (scroll down), the old marks remains. 
The latest code will clear the marks before any action, it should solve this issue.

**Comment by mlin12321** [comment]
That seems to fix it. Thanks!
