### ISSUE TITLE
Setup and experiment guide on readme file

### ISSUE THREAD

**Issue by asuzukosi** [OSU-NLP-Group/SeeAct#4]
I was thinking of adding a setup guide on the readme file, wanted to know if that was something that would be beneficial or if the project is best left as is

**Comment by boyugou** [comment]
Hi Kosi,

Thank you very much for being willing to help me organize the code and readme. 

We will organize the code and readme again when we release the online code (around this Friday). You can consider this at that time, hoping it can save some of your time and efforts.

I assume people will be more curious about the online tool, and the running of that tool will be super easy.
