### ISSUE TITLE
som branch, bounding boxes on out-of-reach elements

### ISSUE THREAD

**Issue by mlin12321** [OSU-NLP-Group/SeeAct#41]
For the som branch, some elements are visible to SeeAct via the html but not on the browser window (for instance, product categories being obscured by search results). However, bounding boxes are still attached to the obscured elements, causing SeeAct to believe it can click on elements that are not there. This can cause timeout issues, especially if SeeAct mistakes the bounding box on the obscured element for the elements on top of it (e.g. a search result covers a category tab, and SeeAct believes the bounding box for the category tab is for the search result).

**Comment by duz-sg** [comment]
Did some searching and found this issue:
https://github.com/microsoft/playwright/issues/9923
And yes, indeed it seems there is no way for us to tell, if there are two elements, one blocking another, which one is clickable. From playwright's point of view, they are both normal elements.

**Comment by boyuanzheng010** [comment]
Solved in: https://github.com/OSU-NLP-Group/SeeAct/issues/41#issuecomment-2198424555
