### ISSUE TITLE
Screenshot not taken with waiting for fonts to load issue

### ISSUE THREAD

**Issue by gum-bunny** [OSU-NLP-Group/SeeAct#49]
Whenever playwright is trying to take a screenshot, this happens

```
Call log:
taking page screenshot
  - waiting for fonts to load...
```

Seems like a playwright issue but don't know of an easy workaround. Any ideas?

**Comment by boyugou** [comment]
I think it's the time for us to switch from using Playwright.page.screenshot to using chrome cdp to take the screenshot (which can be much faster and super stable). @boyuanzheng010  @duz-sg

**Comment by gum-bunny** [comment]
Yeah, it just doesn't allow me to take a screenshot for most websites that aren't PDFs of documents. For that reason, SeeAct isn't able to complete a lot of the tasks that are not of the form "Find me the PDF of the paper XYZ" even though I'm pretty sure it has the ability to.

**Comment by boyugou** [comment]
We were all very busy for many things last few weeks. Will quickly figure it out.

**Comment by gum-bunny** [comment]
Thank you so much! I appreciate the prompt responses and proactiveness. Looking forward to working more on SeeAct!

**Comment by gum-bunny** [comment]
okay I have a quick fix for you

`screenshot_path = await self.capture_screenshot(page, screenshot_path) # put this in async predict in agent.py
# add this method in the agent.py class
async def capture_screenshot(self, page: Page, screenshot_path: str, max_retries=3, delay=2):
        for attempt in range(max_retries):
            try:
                await page.wait_for_load_state('networkidle')
                await page.evaluate('() => document.fonts.ready')
                
                # Scroll to capture full page
                height = await page.evaluate('document.body.scrollHeight')
                await page.set_viewport_size({"width": 1280, "height": height})
                
                screenshot_bytes = await page.screenshot(full_page=True, timeout=90000)
                img = Image.open(io.BytesIO(screenshot_bytes))
                img.save(screenshot_path)
                self.logger.info(f"Screenshot saved: {screenshot_path}")
                return screenshot_path
            except Exception as e:
                self.logger.warning(f"Screenshot attempt {attempt + 1} failed: {e}")
                if attempt < max_retries - 1:
                    await asyncio.sleep(delay)
                else:
                    self.logger.error(f"Failed to capture screenshot after {max_retries} attempts")
                    return None                  
`
this works for me. Let me know if its the same for you or not
