### ISSUE TITLE
keep state between runs

### ISSUE THREAD

**Issue by herval** [OSU-NLP-Group/SeeAct#51]
Is it possible to keep state between runs? Eg if the bot logs in on one given execution, I want it to remain logged in the next time around...

**Comment by boyugou** [comment]
Yes. 

By default, Playwright operates in incognito mode and does not save cookies or other information. There are two ways to retain cookies to avoid repeated logins:

1. Pre-generating the cookies and loading them (storage_state) every time. 

You can write a simple Playwright script and use `page.pause` to manually log into all the sites you want to access, then save the state file from the session. 

Doc of Playwright: [Link](https://playwright.dev/python/docs/auth#reusing-signed-in-state:~:text=Playwright%20provides%20a%20way%20to%20reuse%20the%20signed%2Din%20state%20in%20the%20tests)

2. Modify the current launch method:

```python
self.session_control['browser'] = await normal_launch_async(self.playwright,
                                                            headless=self.config['browser']['headless'] if headless is None else headless,
                                                            args=self.config['browser']['args'] if args is None else args)
self.session_control['context'] = await normal_new_context_async(self.session_control['browser'],
                                                                 viewport=self.config['browser']['viewport'])
```

Change it to Playwright's [persistent launch mode](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context:~:text=Returns%20the%20persistent%20browser%20context%20instance.), which will automatically save the cache and user information each time and run in non-incognito mode (just like humans using a regular browser).

**Comment by boyugou** [comment]
If you have any further questions, please feel free to let us know.
