### ISSUE TITLE
How to get total raw data from globus

### ISSUE THREAD

**Issue by HarryZhou-618** [OSU-NLP-Group/SeeAct#8]
Hi there, I'm trying to get the total raw data from globus, but I'm not familiar with globus. Unfortunately I find that I can only download the single file one by one. How do I download all the files or the total folder at once? Looking forward to your reply~

**Comment by boyuanzheng010** [comment]
Hi @HarryZhou-618 ! Thanks for your interest in our work!
You could refer to OSU-NLP-Group/Mind2Web#28 for some solutions.  This video also provides some help about the process of globus data transfer: https://www.youtube.com/watch?v=jdeMtubk8D4

Hope this can help to solve your problem.
