### ISSUE TITLE
No such file or directory: '../data/formal_manual_selection/task_id_dicts/30_selected.pkl'

### ISSUE THREAD

**Issue by ningyu1991** [OSU-NLP-Group/SeeAct#9]
Thank you for your code and data contributions! Looking forward to your reply about:
No such file or directory: '../data/formal_manual_selection/task_id_dicts/30_selected.pkl'

**Comment by boyuanzheng010** [comment]
Hi, @ningyu1991 , thanks for your interest in our work!
You can download the file along with the query source data in this [link](https://buckeyemailosu-my.sharepoint.com/:f:/g/personal/zheng_2372_buckeyemail_osu_edu/Ei95kzWnWlVAn4DR5I3zDDEBUZtC-9vIf0VBuFMOzZNn2w?e=OcH9Om). The README has also been updated to include this link and simple instruction.
